---
title: "Estimating Proportions with Confidence"
author: "b06208001 龔泓愷"
date: "2018年11月2日"
output: html_document
---
## R Function Practice    
```{r}
Prop_CI_Diff <- function(n1, p1, n2, p2, confd){
  #Group1 Simu
  simu.phat1 = c()
  for (i in 1:10000) {
    phat = sum(sample(c(0,1), n1, replace = T, prob = c(1-p1,p1)))/n1
    simu.phat1[i] = phat
  }
  
  #Group2 Simu
  simu.phat2 = c()
  for (j in 1:10000) {
    phat = sum(sample(c(0,1), n2, replace = T, prob = c(1-p2,p2)))/n2
    simu.phat2[j] = phat
  }
  
  #Diff Phat
  diff.phat = simu.phat1 - simu.phat2
  diff.phat = sort(diff.phat)
  
  #
  low.per = ceiling(((1-confd)/2)*10000)
  low.vlue = diff.phat[low.per]
  high.per = ceiling((1-((1-confd)/2))*10000)
  high.vlue = diff.phat[high.per]
  
  results = c(paste((1-confd)/2*100,"%"), paste((1-((1-confd)/2))*100,"%"), low.vlue, high.vlue)
  
  mean.p = mean(diff.phat)
  sd.p = sd(diff.phat)
  
  CI = list(CI = matrix(results, nrow = 2, byrow = T), mean = mean.p, sd = sd.p, simu = diff.phat)
  
  return(CI)
}
```

###Ex10.10    
```{r}
#Simu
Prop_CI_Diff(1467, 0.624, 1575, 0.490, 0.95)[c('CI','mean', 'sd')]

#Calcu
n1 = 1467
p1 = 0.624
n2 = 1575
p2 = 0.490

mean = p1 - p2;mean
se = sqrt(p1*(1-p1)/n1 + p2*(1-p2)/n2);se
high.c = mean + 1.96 * se;high.c
low.c = mean -1.96 * se;low.c

#Hist
Prop_Diff <- as.numeric(as.character(unlist(Prop_CI_Diff(1467, 0.624, 1575, 0.490, 0.95)['simu'])))
hist(Prop_Diff, probability = T, breaks = 20,
   main = 'The Difference in Two Population proportions',
   xlab = 'The Difference in Two Population proportions',
   col = 'azure3', border = 'white')
abline(v = high.c)
abline(v = low.c)
```

可以看出模擬值與理論計算值十分接近。    
